### ISSUE TITLE
Forward button enables slowly after pressing back

### ISSUE THREAD

**Issue by severinrudie** [mozilla-mobile/firefox-tv#1231]
## Steps to reproduce
- From home
- Navigate to any site
- Open menu
- Press back

### Expected behavior
- Forward should be immediately available

### Actual behavior
- Forward becomes available after around half a second

### Device information

* Fire TV device: Cube, Pendant, Stick, emulator
* Firefox version: c920d79407bc3147e2aab2643d5b67a657012807

**Comment by mcomella** [comment]
Next steps:
- Try on TV
- If reproduce, then file bug for a-c: we think this was working before moving to a-c (maybe look into the code too)

**Comment by Baron-Severin** [comment]
Filed https://github.com/mozilla-mobile/android-components/issues/1311

**Comment by athomasmoz** [comment]
@Baron-Severin I can't reproduce this. Sounds like it may have been fixed by components team, do you mind trying it out again?

**Comment by Baron-Severin** [comment]
Still reproducible for me, unfortunately
Device: Cube
Version: 234acb430dcec7423be7d7dd5191cd3e23186b2b

![slow-forward-enable](https://user-images.githubusercontent.com/13170306/50305353-6bd7ba80-0447-11e9-9b68-1265a04201f0.gif)

**Comment by pocmo** [comment]
A fix for this was released with 0.33.0. Is this still an issue? Tentatively removing the a-c label here. Please file a new AC issue if you are still seeing problems.

**Comment by dnarcese** [comment]
This is fixed, closing.
